version: "3.5"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    image: Camagru/backend
    container_name: backend
    volumes:
      - ./backend/:/camagru/backend:ro
    networks:
      camagru_network:
        aliases: [camagru.backend]
    depends_on:
      postgres: { condition: service_healthy }
    ports:
      - 3000:3000
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    image: Camagru/frontend
    container_name: frontend
    volumes:
      - ./frontend/:/camagru/frontend:ro
    ports:
      - 4200:4200
    networks:
      camagru_network:
        aliases: [camagru.frontend]
    restart: on-failure

networks:
  camagru_network:
    driver: bridge