version: "3.5"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: node app.js
    image: camagru-backend
    container_name: backend
    volumes:
      - ./backend/:/camagru-backend:ro
    networks:
      camagru_network:
        aliases: [camagru.backend]
    ports:
      - 3000:3000
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    command: node app.js
    image: camagru-frontend
    container_name: frontend
    volumes:
      - ./frontend/:/camagru-frontend:ro
    ports:
      - 6300:6300
    networks:
      camagru_network:
        aliases: [camagru.frontend]
    restart: on-failure

networks:
  camagru_network:
    driver: bridge